import test from "node:test";
import assert from "node:assert/strict";
import React from "react";
import { renderToStaticMarkup } from "react-dom/server";

// Markdown.res.mjs is generated by `rescript build` (run as part of `npm run build`).
import * as Markdown from "../client/src/components/Markdown.res.mjs";

const render = (text) => renderToStaticMarkup(React.createElement(Markdown.make, { text }));

test("renders bold inside a paragraph", () => {
  const html = render("Hello **world**");
  assert.match(html, /<strong[^>]*>world<\/strong>/);
  assert.match(html, /<p[^>]*>/);
});

test("renders italic and inline code", () => {
  assert.match(render("an _emphasis_ here"), /<em[^>]*>emphasis<\/em>/);
  assert.match(render("run `npm run build` now"), /<code[^>]*>npm run build<\/code>/);
});

test("renders an unordered list with one <li> per item", () => {
  const html = render("* one\n* two\n* three");
  assert.match(html, /<ul[^>]*>/);
  assert.equal((html.match(/<li[^>]*>/g) || []).length, 3);
});

test("renders an ordered list", () => {
  const html = render("1. first\n2. second");
  assert.match(html, /<ol[^>]*>/);
  assert.equal((html.match(/<li[^>]*>/g) || []).length, 2);
});

test("renders a fenced code block verbatim", () => {
  const html = render("```\nline1\nline2\n```");
  assert.match(html, /<pre[^>]*>[\s\S]*line1[\s\S]*line2[\s\S]*<\/pre>/);
});

test("allows safe links and keeps the href", () => {
  const html = render("see [my site](https://arda.tr)");
  assert.match(html, /<a [^>]*href="https:\/\/arda\.tr"[^>]*>my site<\/a>/);
});

test("drops javascript: links to plain text (no anchor, no scheme leak)", () => {
  const html = render("[click](javascript:alert(1))");
  assert.doesNotMatch(html, /<a /);
  assert.doesNotMatch(html, /javascript:/);
  assert.match(html, /click/);
});

test("escapes raw HTML so model output cannot inject markup", () => {
  const html = render('<img src=x onerror="alert(1)">');
  assert.doesNotMatch(html, /<img/);
  assert.match(html, /&lt;img/);
});

test("empty input renders without throwing", () => {
  assert.doesNotThrow(() => render(""));
});
